if (!require("BiocManager", quietly = TRUE))
    install.packages("BiocManager")
if (!require("graph", quietly = TRUE))
    BiocManager::install("graph")
if (!require("RBGL", quietly = TRUE))
    BiocManager::install("RBGL")
if (!require("pcalg", quietly = TRUE))
    install.packages('pcalg')
if (!require("kpcalg", quietly = TRUE))
    install.packages('kpcalg')
if (!require("bnlearn", quietly = TRUE))
    install.packages('bnlearn')
if (!require("sparsebn", quietly = TRUE))
    install.packages('sparsebn')
if (!require("SID", quietly = TRUE))
    install.packages('SID')
if (!require("CAM", quietly = TRUE))
    install.packages('CAM')
if (!require("D2C", quietly = TRUE))
    install.packages('D2C')
if (!require("devtools", quietly = TRUE))
    install.packages('devtools')
if (!require("RCIT", quietly = TRUE))
    library(devtools)
    install_github("Diviyan-Kalainathan/RCIT")
